# -*- mode: sh -*-
#
# Clerk organization ID cache.
#
# Fetches org IDs from Clerk across all environments and caches them
# as env vars. Sourced automatically on shell startup; call
# `clerk-refresh-orgs` to update the cache.
#

typeset -g CLERK_ORGS_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/clerk-orgs.zsh"

# Refresh the Clerk org ID cache.
# Fetches internal orgs from each environment (staging/preprod/prod)
# and all customer orgs from prod, then writes them as env vars.
clerk-refresh-orgs() {
  (( $+commands[clerk] )) || { print -u2 "clerk not found"; return 1; }

  local cache_dir="${CLERK_ORGS_CACHE:h}"
  mkdir -p "$cache_dir"

  local tmp
  tmp=$(mktemp) || return 1

  {
    print "# Auto-generated by clerk-refresh-orgs on $(date -u +\"%Y-%m-%dT%H:%M:%SZ\")"
    print "# Re-run 'clerk-refresh-orgs' to update.\n"

    # ── Internal orgs per environment ──────────────────────────────
    # Format: env_name  env_key  slug  var_prefix
    # slug may differ across environments (e.g. sawmills-o11y vs sawmills-olly)
    local -a internal_orgs=(
      staging  CLERK_KEY_STAGING  sawmills      ""
      staging  CLERK_KEY_STAGING  sawmills-o11y OLLY
      preprod  CLERK_KEY_PREPROD  sawmills      ""
      preprod  CLERK_KEY_PREPROD  sawmills-o11y OLLY
      prod     CLERK_KEY_PROD     sawmills      ""
      prod     CLERK_KEY_PROD     sawmills-olly OLLY
    )

    local env_name env_key slug prefix org_id var_name
    local i=1
    while (( i <= ${#internal_orgs} )); do
      env_name=${internal_orgs[$i]}
      env_key=${internal_orgs[$((i+1))]}
      slug=${internal_orgs[$((i+2))]}
      prefix=${internal_orgs[$((i+3))]}
      (( i += 4 ))

      org_id=$(CLERK_API_KEY="${(P)env_key}" clerk orgs "$slug" --id-only 2>/dev/null)
      if [[ -n "$org_id" ]]; then
        if [[ -n "$prefix" ]]; then
          var_name="${(U)env_name}_${prefix}_ORG_ID"
        else
          var_name="${(U)env_name}_ORG_ID"
        fi
        print "export ${var_name}=${(q)org_id}"
      else
        print -u2 "warn: could not resolve $slug org for $env_name"
      fi
    done

    print ""

    # ── All customer orgs from prod ───────────────────────────────
    local line org cust_slug
    CLERK_API_KEY="${CLERK_KEY_PROD}" clerk orgs list --limit 500 2>/dev/null | while IFS= read -r line; do
      # Match data rows: │ org_xxx ┆ Name ┆ slug │
      if [[ "$line" =~ '│[[:space:]]*(org_[A-Za-z0-9]+)[[:space:]]*┆[^┆]*┆[[:space:]]*([A-Za-z0-9_-]+)[[:space:]]*│' ]]; then
        org="${match[1]}"
        cust_slug="${match[2]}"
        var_name="${${cust_slug//-/_}:u}_ORG_ID"
        print "export ${var_name}=${(q)org}"
      fi
    done
  } >| "$tmp"

  command mv -f "$tmp" "$CLERK_ORGS_CACHE"
  source "$CLERK_ORGS_CACHE"
  print "Clerk org cache updated: $CLERK_ORGS_CACHE"
}
