# -*- mode: sh -*-
#
# Clerk organization ID cache.
#
# Fetches org IDs from Clerk across all environments and caches them
# as env vars. Sourced automatically on shell startup; call
# `clerk-refresh-orgs` to update the cache.
#

typeset -g CLERK_ORGS_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/clerk-orgs.zsh"

# Refresh the Clerk org ID cache.
# Lists all orgs in each environment (staging/preprod/prod) and exports them
# as env-prefixed vars: ${ENV}_${SLUG}_ORG_ID.
# Prod orgs are also exported without the prefix for convenience.
clerk-refresh-orgs() {
  (( $+commands[clerk] )) || { print -u2 "clerk not found"; return 1; }

  local cache_dir="${CLERK_ORGS_CACHE:h}"
  mkdir -p "$cache_dir"

  local tmp
  tmp=$(mktemp) || return 1

  # Parse clerk orgs list output into "export VAR=value" lines.
  # Args: $1=env_prefix (e.g. STAGING), $2=CLERK_KEY var name
  # Optionally pass "also_unprefixed" as $3 to emit SLUG_ORG_ID too.
  _clerk_list_env() {
    local env_prefix=$1 key_var=$2 also_unprefixed=$3
    local line org slug var_name

    CLERK_API_KEY="${(P)key_var}" clerk orgs list --limit 500 2>/dev/null | while IFS= read -r line; do
      if [[ "$line" =~ '│[[:space:]]*(org_[A-Za-z0-9]+)[[:space:]]*┆[^┆]*┆[[:space:]]*([A-Za-z0-9_-]+)[[:space:]]*│' ]]; then
        org="${match[1]}"
        slug="${match[2]}"
        var_name="${${slug//-/_}:u}_ORG_ID"
        print "export ${env_prefix}_${var_name}=${(q)org}"
        [[ "$also_unprefixed" == "also_unprefixed" ]] && \
          print "export ${var_name}=${(q)org}"
      fi
    done
  }

  {
    print "# Auto-generated by clerk-refresh-orgs on $(date -u +\"%Y-%m-%dT%H:%M:%SZ\")"
    print "# Re-run 'clerk-refresh-orgs' to update.\n"

    print "# ── Staging ──"
    _clerk_list_env STAGING CLERK_KEY_STAGING
    print ""

    print "# ── Preprod ──"
    _clerk_list_env PREPROD CLERK_KEY_PREPROD
    print ""

    print "# ── Prod (also exported without prefix) ──"
    _clerk_list_env PROD CLERK_KEY_PROD also_unprefixed
  } >| "$tmp"

  unfunction _clerk_list_env 2>/dev/null

  command mv -f "$tmp" "$CLERK_ORGS_CACHE"
  source "$CLERK_ORGS_CACHE"
  print "Clerk org cache updated: $CLERK_ORGS_CACHE"
}
