# -*- mode: sh -*-
#
# Clerk organization ID cache.
#
# Fetches org IDs from Clerk across all environments and caches them
# as env vars. Sourced automatically on shell startup; call
# `clerk-refresh-orgs` to update the cache.
#

typeset -g CLERK_ORGS_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/clerk-orgs.zsh"

# Refresh the Clerk org ID cache.
# Fetches the Sawmills org from each environment (staging/preprod/prod)
# and all customer orgs from prod, then writes them as env vars.
clerk-refresh-orgs() {
  (( $+commands[clerk] )) || { print -u2 "clerk not found"; return 1; }

  local cache_dir="${CLERK_ORGS_CACHE:h}"
  mkdir -p "$cache_dir"

  local tmp
  tmp=$(mktemp) || return 1

  {
    print "# Auto-generated by clerk-refresh-orgs on $(date -u +\"%Y-%m-%dT%H:%M:%SZ\")"
    print "# Re-run 'clerk-refresh-orgs' to update.\n"

    # Internal Sawmills org per environment
    local env_name env_key org_id
    for env_name env_key in staging CLERK_KEY_STAGING preprod CLERK_KEY_PREPROD prod CLERK_KEY_PROD; do
      org_id=$(CLERK_API_KEY="${(P)env_key}" clerk orgs sawmills --id-only 2>/dev/null)
      if [[ -n "$org_id" ]]; then
        print "export ${(U)env_name}_ORG_ID=${(q)org_id}"
      else
        print -u2 "warn: could not resolve sawmills org for $env_name"
      fi
    done

    print ""

    # All customer orgs from prod — parse the table into SLUG_ORG_ID=org_xxx
    local line org slug
    CLERK_API_KEY="${CLERK_KEY_PROD}" clerk orgs list --limit 500 2>/dev/null | while IFS= read -r line; do
      # Match data rows: │ org_xxx ┆ Name ┆ slug │
      if [[ "$line" =~ '│[[:space:]]*(org_[A-Za-z0-9]+)[[:space:]]*┆[^┆]*┆[[:space:]]*([A-Za-z0-9_-]+)[[:space:]]*│' ]]; then
        org="${match[1]}"
        slug="${match[2]}"
        # Convert slug to env var name: my-company -> MY_COMPANY_ORG_ID
        local var_name="${${slug//-/_}:u}_ORG_ID"
        print "export ${var_name}=${(q)org}"
      fi
    done
  } > "$tmp"

  mv "$tmp" "$CLERK_ORGS_CACHE"
  source "$CLERK_ORGS_CACHE"
  print "Clerk org cache updated: $CLERK_ORGS_CACHE"
}
