#!/bin/bash
# rotate-password - Rotate passwords to get back to desired one
# Usage: rotate-password [rotations]  (default: 7)

set -e

USER=$(whoami)
ROTATIONS=${1:-7}

read -sp "Current password: " CURRENT
echo
read -sp "Target password: " TARGET
echo

PREV="$CURRENT"

for i in $(seq 1 $ROTATIONS); do
    # Generate hash without consecutive chars
    while true; do
        HASH=$(echo "${RANDOM}${RANDOM}" | md5 | cut -c1-6)
        if ! echo "$HASH" | grep -qE '(.)\1'; then
            break
        fi
    done
    TEMP="Zk${HASH}!q${i}@x#"
    echo "Rotation $i/$ROTATIONS... (temp: $TEMP)"
    dscl . -passwd /Users/$USER "$PREV" "$TEMP"
    PREV="$TEMP"
done

echo "Final rotation to target..."
dscl . -passwd /Users/$USER "$PREV" "$TARGET"

echo "Done. Password set to target."
