#!/usr/bin/env bash

#
# Install OS X-specific dependencies.
#

set -o errexit
set -o nounset
set -o pipefail

CURRENT_SCRIPT_PATH="$(cd "$(dirname "$0")" ; pwd -P)"

CASKS_LIST="${CURRENT_SCRIPT_PATH}/casks.txt"
PACKAGES_LIST="${CURRENT_SCRIPT_PATH}/packages.txt"
TAPS_LIST="${CURRENT_SCRIPT_PATH}/taps.txt"

if ! command -v brew > /dev/null 2>&1; then
  echo "ERROR: Could not find brew. Please install brew and re-run this script."
  exit 1
fi

brew update

while read -r tap; do
  HOMEBREW_NO_AUTO_UPDATE=1 brew tap ${tap}
done < "${TAPS_LIST}"

while read -r package; do
  HOMEBREW_NO_AUTO_UPDATE=1 brew cask install ${package} --no-quarantine
done < "${CASKS_LIST}"

while read -r package; do
  HOMEBREW_NO_AUTO_UPDATE=1 brew install ${package}
done < "${PACKAGES_LIST}"


# Print a warning for any taps that are not committed to taps.txt
for tap in $(echo "$(cat "${TAPS_LIST}")" "$(cat "${TAPS_LIST}")" "$(brew tap)" | tr ' ' '\n' | sort | uniq -u); do
  echo "Found extraneous tapped homebrew tap ${tap}; consider adding it to taps.txt."
done

# Print a warning for any casks that are not committed to casks.txt
for package in $(echo "$(cat "${CASKS_LIST}")" "$(cat "${CASKS_LIST}")" "$(brew cask list)" | tr ' ' '\n' | sort | uniq -u); do
  echo "Found extraneous installed homebrew cask ${package}; consider adding it to casks.txt."
done

for setup_script in ${CURRENT_SCRIPT_PATH}/setup/*.sh ; do
   "${setup_script}"
done

# Add installed java versions to jenv
for version in /Library/Java/JavaVirtualMachines/* ; do
  jenv add ${version}/Contents/Home/
done

# Set java version to 8
jenv global 1.8
