#!/usr/bin/env bash

ROOT_PATH="$(cd "$(dirname "$0")/.." ; pwd -P)"

#
# Link dotfiles
#

packages=(
  "bin"
  "git"
  "zsh"
  "macos"
)

echo "Symlinking dotfiles from ${ROOT_PATH} into ${HOME}..."
for pkg in "${packages[@]}"; do
    cd ${ROOT_PATH}
    stow --target="$HOME" --verbose=1 "${pkg}"
done
echo "Symlinked dotfiles into $HOME."
